apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scrape-platform.fullname" . }}-secrets
  labels:
    {{- include "scrape-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis-password: {{ .Values.redis.password | default "changeme" | quote }}
  bull-board-password: {{ .Values.bullBoardPassword | default "changeme" | quote }}
