apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: scrape-system

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - redis-deployment.yaml
  - api-deployment.yaml
  - worker-deployment.yaml
  - web-deployment.yaml
  - hpa.yaml
  - network-policies.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: scrape-platform
